/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package joker;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import okhttp3.OkHttpClient;
import okhttp3.Request;

/**
 *
 * @author user
 */
public class JokerJFrame1 extends javax.swing.JFrame {

    //Entity Manager & Controllers
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("JokerPU");
    EntityManager em = emf.createEntityManager();
    EntityTransaction tx = em.getTransaction();
    GameJpaController gjc = new GameJpaController(emf);
    PrizecategoriesJpaController pjc = new PrizecategoriesJpaController(emf);

    /**
     * Creates new form JokerJFrame1
     */
    public JokerJFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("1. Διαχείριση δεδομένων ΤΖΟΚΕΡ");

        jLabel2.setText("Id Παιχνιδιού");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Εμφάνιση δεδομένων");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Από Ημερομηνία");

        jLabel4.setText("Έως Ημερομηνία");

        jButton2.setText("Εύρεση Παιχνιδιών");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("ΝΙΚΗΤΡΙΑ ΣΤΗΛΗ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "1ος", "2ος", "3ος", "4ος", "5ος", "Joker"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"5+1", null, null},
                {"5", null, null},
                {"4+1", null, null},
                {"4", null, null},
                {"3+1", null, null},
                {"3", null, null},
                {"2+1", null, null},
                {"1+1", null, null}
            },
            new String [] {
                "Κατηγορίες επιτυχιών", "Επιτυχίες", "Κέρδη ανά επιτυχία"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Id Παιχνιδιών");

        jButton3.setText("Αποθήκευση δεδομένων");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Διαγραφή δεδομένων παιχνιδιού");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Διαγραφή δεδομένων παιχνιδιών εντός εύρους ημερομηνιών");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(42, 56, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2)
                                    .addComponent(jLabel6)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                        .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(174, 174, 174))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButton3)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jButton4)
                        .addGap(30, 30, 30)
                        .addComponent(jButton5)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Το url που θα καλέσουμε
        String select = jTextField1.getText();
        String urlToCall = "https://api.opap.gr/draws/v3.0/5104/" + select;
        System.out.println(urlToCall);

        //Δημιουργούμε ένα αντικείμενο OkHttpClient 
        OkHttpClient client = new OkHttpClient();
        //Δημιουργούμε ένα αντικείμενο Request με όρισμα το url που θα καλέσουμε 
        Request request = new Request.Builder().url(urlToCall).build();

        //Ξεκινάμε και ζητάμε το url και ελέγχουμε εάν μας φέρνει αποτελέσματα
        try (okhttp3.Response response = client.newCall(request).execute()) {
            if (response.isSuccessful() && response.body() != null) {

                //Καταχωρούμε σε ένα String το αποτέλεσμα
                String responseString = response.body().string();

                //Δημιουργούμε ένα αντικείμενο GsonBuilder
                GsonBuilder builder = new GsonBuilder();
                builder.setPrettyPrinting();
                Gson gson = builder.create();

                //Πέρνουμε τα αποτελέσματα σε JsonObject και δημιουργούμε ένα JsonArray
                JsonObject json = gson.fromJson(responseString, JsonObject.class);
                System.out.println(json);

                JsonObject winningNumbers = json.getAsJsonObject("winningNumbers");
                System.out.println(winningNumbers);
                JsonArray numbers = winningNumbers.get("list").getAsJsonArray();
                JsonArray joker = winningNumbers.get("bonus").getAsJsonArray();
                System.out.println(numbers);
                System.out.println(joker);

                //Δημιουργούμε 2 models για τους πίνακες
                DefaultTableModel model = new DefaultTableModel();
                DefaultTableModel model2 = new DefaultTableModel();

                //Ορίζουμε τις επικεφαλίδες στους πίνακες
                model.setColumnIdentifiers(new String[]{"1oς", "2oς", "3oς", "4oς", "5oς", "Joker"});
                model2.setColumnIdentifiers(new String[]{"Κατηγορίες επιτυχιών", "Επιτυχίες", "Κέρδη ανά επιτυχία"});

                String[] n = new String[6];
                for (int i = 0; i < numbers.size(); i++) {
                    n[i] = numbers.get(i).getAsString();
                }
                n[5] = joker.getAsString();
                model.addRow(n);

                //Στοίχιση δεδομένων πίνακων στο κέντρο
                DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
                jTable1.setDefaultRenderer(Object.class, centerRenderer);
                jTable1.setModel(model);

                //JsonObject prizeCategories = last.getAsJsonObject("prizeCategories");
                JsonArray prizeCategories = json.get("prizeCategories").getAsJsonArray();
                System.out.println(prizeCategories);
                String[] p = new String[3];

                //Διαπερνάμε τα JsonElements
                for (JsonElement element : prizeCategories) {
                    switch (element.getAsJsonObject().get("id").getAsInt()) {
                        case 1:
                            p[0] = "5+1";
                            break;
                        case 2:
                            p[0] = "5";
                            break;
                        case 3:
                            p[0] = "4+1";
                            break;
                        case 4:
                            p[0] = "4";
                            break;
                        case 5:
                            p[0] = "3+1";
                            break;
                        case 6:
                            p[0] = "3";
                            break;
                        case 7:
                            p[0] = "2+1";
                            break;
                        case 8:
                            p[0] = "1+1";
                            break;
                    }
                    p[1] = element.getAsJsonObject().get("winners").getAsString();
                    p[2] = element.getAsJsonObject().get("divident").getAsString();
                    model2.addRow(p);
                }

                //Στοίχιση δεδομένων πίνακων στο κέντρο
                DefaultTableCellRenderer centerRenderer2 = new DefaultTableCellRenderer();
                centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
                jTable2.setDefaultRenderer(Object.class, centerRenderer);
                jTable2.setModel(model2);

                // Ενημερωτικό μύνημα
                JOptionPane.showMessageDialog(null, "Τα δεδομένα για το gameId: " + select + " εισήχθησαν", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // Ενημερωτικό μύνημα
                JOptionPane.showMessageDialog(null, "Δεν υπάρχουν δεδομένα για το gameId: " + select, "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            // Ενημερωτικό μύνημα
            JOptionPane.showMessageDialog(null, "Δεν υπάρχουν δεδομένα για το gameId: " + select, "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //προβάλλονται οι λεπτομέρειες για όσα παιχνίδια έχουν γίνει εντός τους εύρους ημερομηνιών
        try {
            //Οι ημερομηνίες που επέλεξε ο χρήστης
            Date date1 = jDateChooser1.getDate();
            Date date2 = jDateChooser2.getDate();
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat format2 = new SimpleDateFormat("dd-MM-yyyy");
            String stringDate1 = format.format(date1);
            String stringDate2 = format.format(date2);
            System.out.println(stringDate1 + stringDate2);

            //Το url που θα καλέσουμε
            String urlToCall = "https://api.opap.gr/draws/v3.0/5104/draw-date/" + stringDate1 + "/" + stringDate2 + "/draw-id";
            System.out.println(urlToCall);

            //Δημιουργούμε ένα αντικείμενο OkHttpClient 
            OkHttpClient client = new OkHttpClient();
            //Δημιουργούμε ένα αντικείμενο Request με όρισμα το url που θα καλέσουμε 
            Request request = new Request.Builder().url(urlToCall).build();

            //Ξεκινάμε και ζητάμε το url και ελέγχουμε εάν μας φέρνει αποτελέσματα
            try (okhttp3.Response response = client.newCall(request).execute()) {

                if (response.isSuccessful() && response.body() != null) {

                    //Καταχωρούμε σε ένα String το αποτέλεσμα
                    String responseString = response.body().string();

                    //Δημιουργούμε ένα αντικείμενο GsonBuilder
                    GsonBuilder builder = new GsonBuilder();
                    builder.setPrettyPrinting();
                    Gson gson = builder.create();
                    //Πέρνουμε τα αποτελέσματα σε JsonObject και δημιουργούμε ένα JsonArray
                    JsonArray json = gson.fromJson(responseString, JsonArray.class);

                    System.out.println(json);

                    //Δημιουργώ ένα Model
                    DefaultComboBoxModel model = new DefaultComboBoxModel();

                    //Διαπερνάω τα δεδομένα id παιχνιδιών
                    for (JsonElement jsonElement : json) {
                        String data = jsonElement.getAsString();
                        model.addElement(data);
                    }

                    //Προσθέτω τα drawid στο jComboBox1
                    jComboBox1.setModel(model);

                    // Ενημερωτικό μύνημα
                    JOptionPane.showMessageDialog(null, "Τα δεδομένα για τα παιχνίδια από " + format2.format(date1)
                            + " έως " + format2.format(date2) + " εισήχθησαν", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    // Ενημερωτικό μύνημα
                    JOptionPane.showMessageDialog(null, "Δεν υπάρχουν διοαθέσιμα δεδομένα από " + format2.format(date1)
                            + " έως " + format2.format(date2), "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception ex) {
                // Ενημερωτικό μύνημα
                JOptionPane.showMessageDialog(null, "Δεν υπάρχουν διοαθέσιμα δεδομένα από " + format2.format(date1)
                        + " έως " + format2.format(date2), "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            // Ενημερωτικό μύνημα
            JOptionPane.showMessageDialog(null, "Παρακαλώ επιλέξτε το εύρος των ημερομηνιών", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jComboBox1.getSelectedItem().toString());
        this.jButton1ActionPerformed(evt);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int drawId = Integer.parseInt(jTextField1.getText());
        System.out.println(drawId);

        Query query = em.createNamedQuery("Game.findByDrawid");
        query.setParameter("drawid", drawId);

        //Ελέγχουμε εάν υπάρχουν δεδομένα στην Database
        if (query.getResultList().isEmpty()) {
            try {
                int number1 = Integer.parseInt(jTable1.getValueAt(0, 0).toString());
                int number2 = Integer.parseInt(jTable1.getValueAt(0, 1).toString());
                int number3 = Integer.parseInt(jTable1.getValueAt(0, 2).toString());
                int number4 = Integer.parseInt(jTable1.getValueAt(0, 3).toString());
                int number5 = Integer.parseInt(jTable1.getValueAt(0, 4).toString());
                int joker = Integer.parseInt(jTable1.getValueAt(0, 5).toString());

                Game g = new Game(drawId, number1, number2, number3, number4, number5, joker);
                //Με τον GameJpaController στέλνουμε το αντικείμενο στην Database
                gjc.create(g);

                int j = 0;
                for (int i = 0; i <= 7; i++) {
                    int winners = Integer.parseInt(jTable2.getValueAt(i, 1).toString());
                    double divident = Double.parseDouble(jTable2.getValueAt(i, 2).toString());
                    System.out.println(winners + " " + divident);
                    Prizecategories p = new Prizecategories(i, winners, divident, g);
                    //PrizecategoriesJpaController
                    pjc.create(p);
                }

                // Ενημερωτικό μύνημα
                JOptionPane.showMessageDialog(null, "Το παιχνίδι καταχωρήθηκε στην βάση δεδομένων ", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                // Ενημερωτικό μύνημα
                System.out.println(ex);
                JOptionPane.showMessageDialog(null, "Το παιχνίδι δεν καταχωρήθηκε στην βάση δεδομένων ", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Το παιχνίδι υπάρχει ήδη στην βάση δεδομένων ", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Με την επιλογή της διαγραφής δεδομένων παιχνιδιού διαγράφονται από τη βάση δεδομένων
        //τα σχετικά δεδομένα βάζει του id του εν λόγω παιχνιδιού 
        //Η ολοκλήρωση οποιασδήποτε διαγραφής δεδομένων γίνεται αφού προηγηθεί 
        //ερώτημα επαλήθευσης με επιβεβαίωση από το χρήστη.
        int option = JOptionPane.showConfirmDialog(null, "Tο σύστημα θα διαγράψει από τη βάση δεδομένων τα δεδομένα \n"
                + "του παιχνιδιού με drawId " + jTextField1.getText() + ".\nΕίστε βέβαιοι;",
                "Διαγραφή Δεδομένων", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            try {
                // Διαγραφή Prizecategories & Game
                tx.begin();
                int drawid = Integer.parseInt(jTextField1.getText().toString());
                Game gamedrawid = gjc.findGame(drawid);

                // Διαγραφή Prizecategories
                Query query = em.createQuery("DELETE FROM Prizecategories p WHERE p.gamedrawid = :gamedrawid");
                query.setParameter("gamedrawid", gamedrawid).executeUpdate();

                // Διαγραφή Game
                Query query2 = em.createQuery("DELETE FROM Game g WHERE g.drawid = :drawid");
                query2.setParameter("drawid", drawid).executeUpdate();
                tx.commit();
                JOptionPane.showMessageDialog(null, "Τα δεδομένα του drawid:" + drawid + " διαγράφηκαν από την Database", "Διαγραφή Δεδομένων",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                System.out.println(ex);
            }
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //και αντίστοιχα υλοποιείται και η διαγραφή παιχνιδιών εντός ορισμένου εύρους ημερομηνιών.
        //Το url που θα καλέσουμε
        try {
            Date date1 = jDateChooser1.getDate();
            Date date2 = jDateChooser2.getDate();
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            String stringDate1 = format.format(date1);
            String stringDate2 = format.format(date2);
            System.out.println(stringDate1 + stringDate2);
            String urlToCall = "https://api.opap.gr/draws/v3.0/5104/draw-date/" + stringDate1 + "/" + stringDate2 + "/draw-id";
            System.out.println(urlToCall);
            //Δημιουργούμε ένα αντικείμενο OkHttpClient 
            OkHttpClient client = new OkHttpClient();
            //Δημιουργούμε ένα αντικείμενο Request με όρισμα το url που θα καλέσουμε 
            Request request = new Request.Builder().url(urlToCall).build();

            //Ξεκινάμε και ζητάμε το url και ελέγχουμε εάν μας φέρνει αποτελέσματα
            try (okhttp3.Response response = client.newCall(request).execute()) {

                if (response.isSuccessful() && response.body() != null) {

                    //Καταχωρούμε σε ένα String το αποτέλεσμα
                    String responseString = response.body().string();

                    //Δημιουργούμε ένα αντικείμενο GsonBuilder
                    GsonBuilder builder = new GsonBuilder();
                    builder.setPrettyPrinting();
                    Gson gson = builder.create();
                    //Πέρνουμε τα αποτελέσματα σε JsonObject και δημιουργούμε ένα JsonArray
                    JsonArray json = gson.fromJson(responseString, JsonArray.class);

                    System.out.println(json);

                    int option = JOptionPane.showConfirmDialog(null, "Tο σύστημα θα διαγράψει από τη βάση δεδομένων τα δεδομένα \n"
                            + "των παιχνιδιών με drawId: " + json + "\nΕίστε βέβαιοι;",
                            "Διαγραφή Δεδομένων", JOptionPane.YES_NO_OPTION);
                    if (option == JOptionPane.YES_OPTION) {
                        try {
                            // Διαγραφή Prizecategories & Games
                            tx.begin();
                            String start = json.get(0).getAsString();
                            String end = json.get(json.size() - 1).getAsString();
                            // Διαγραφή Prizecategories
                            Query query = em.createNativeQuery("DELETE FROM Prizecategories WHERE gamedrawid BETWEEN " + start + " AND " + end);
                            query.executeUpdate();

                            // Διαγραφή Games
                            Query query2 = em.createNativeQuery("DELETE FROM Game WHERE drawid BETWEEN " + start + " AND " + end);
                            query2.executeUpdate();
                            tx.commit();
                            JOptionPane.showMessageDialog(null, "Τα δεδομένα των drawid: " + json + "\nδιαγράφηκαν από την Database", "Διαγραφή Δεδομένων",
                                    JOptionPane.INFORMATION_MESSAGE);
                        } catch (Exception ex) {
                            System.out.println(ex);
                        }
                    }

                } else {
                    // Ενημερωτικό μύνημα
                    JOptionPane.showMessageDialog(null, "Δεν υπάρχουν δεδομένα", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception ex) {
                // Ενημερωτικό μύνημα
                System.out.println(ex);
                JOptionPane.showMessageDialog(null, "Δεν υπάρχουν δεδομένα", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);

            }
        } catch (Exception ex) {
            // Ενημερωτικό μύνημα
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Παρακαλώ επιλέξτε το εύρος των ημερομηνιών", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JokerJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JokerJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JokerJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JokerJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JokerJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
